{% set name = "hishel" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hishel-{{ version }}.tar.gz
  sha256: 6643450bfb1cfa2ecd6002769f6f5069d0d048c9c1f1e29a98a48302d5875092


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-fancy-pypi-readme
    - pip
  run:
    - python >={{ python_min }}
    - httpx >=0.28.0

test:
  imports:
    - hishel
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/karpetrosyan/hishel
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Persistent cache implementation for httpx and httpcore
  doc_url: https://hishel.com
  dev_url: https://github.com/karpetrosyan/hishel

extra:
  recipe-maintainers:
    - karpetrosyan
    - parkerhancock
    - xhochy
