{% set name = "hishel" %}
{% set version = "0.0.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hishel-{{ version }}.tar.gz
  sha256: ddb22ee32c656e3c75cd05efefd1165c5fbd1c3f023edffda684f5125625700b


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-fancy-pypi-readme
    - pip
  run:
    - python >=3.8
    - httpx >=0.22.0

test:
  imports:
    - hishel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/karpetrosyan/hishel
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Persistent cache implementation for httpx and httpcore
  doc_url: https://hishel.com
  dev_url: https://github.com/karpetrosyan/hishel

extra:
  recipe-maintainers:
    - karpetrosyan
    - parkerhancock
