schema_version: 1

context:
  name: hishel
  version: "1.1.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/hishel-${{ version }}.tar.gz
  sha256: e3a01d8f14542d8c514c7b4f18d3b58c2c48564c0b2130da801a09c7280d8993

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-fancy-pypi-readme
    - pip
  run:
    - python >=${{ python_min }}
    - msgpack-python >=1.1.2
    - typing_extensions >=4.14.1
tests:
  - python:
      imports:
        - hishel
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Persistent cache implementation for httpx and httpcore
  homepage: https://github.com/karpetrosyan/hishel
  repository: https://github.com/karpetrosyan/hishel
  documentation: https://hishel.com

extra:
  recipe-maintainers:
    - karpetrosyan
    - parkerhancock
    - xhochy
