schema_version: 1

context:
  name: hishel
  version: "1.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/hishel-${{ version }}.tar.gz
  sha256: 4fd61c5a68fe0ed45ceeb6e137e11d8d7d03a15822b50e4281f9d5afc1468a0c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-fancy-pypi-readme
    - pip
  run:
    - python >=${{ python_min }}
    - httpx >=0.28.0

tests:
  - python:
      imports:
        - hishel
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Persistent cache implementation for httpx and httpcore
  homepage: https://github.com/karpetrosyan/hishel
  repository: https://github.com/karpetrosyan/hishel
  documentation: https://hishel.com

extra:
  recipe-maintainers:
    - karpetrosyan
    - parkerhancock
    - xhochy
